### ISSUE TITLE
[Hugo] CSS für Quellenhinweis für light-/dark-Mode anpassen

### ISSUE THREAD

**Issue by cagix** [cagix/pandoc-lecture#39]
In `hugo/hugo-lecture/layouts/partials/custom-header.html` wird für die Quellenhinweise (Span `.origin`) die Schriftart festgelegt und ein leicht grauer Hintergrund definiert:

```css
.origin {
    background-color: #ededed;
    font-size: 0.8em;
}
```

Das kann man im dark-Mode nicht mehr gut lesen. Entweder anpassen und zwei verschiedene Definitionen für light- vs. dark-Mode oder Einbindung vorhandener Möglichkeiten aus dem Theme ([Icon](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/icon/index.html), [Notice](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/notice/index.html))?
